server:
  port: 8080
spring:
  application:
    name: StorageMaster
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.1.104:30336}/storage_master?createDatabaseIfNotExist=true&serverTimezone=CTT
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect